server:
  port: 8222
spring:
  application:
    name: myshop-gateway-gt
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
  instance:
    prefer-ip-address: true
#zuul的动态路由配置
zuul:
  routes:
    myshop-user-gt:
      path: /myshop-user-gt  # 需要转发的路径
      serviceId: myshop-user-gt # 最终转发的微服务（名称）
    myshop-web-gt:
      path: /myshop-web-gt  # 需要转发的路径
      serviceId: myshop-web-gt # 最终转发的微服务（名称）
# 让zuul预定义的异常过滤器失效
  SendErrorFilter:
    error:
      disable: true


